Repository duckdb/duckdb-rs, pull requests merged in 2021-09, with the labels that each got.

#20 feat: impl config
  Cargo.toml
  src/config.rs
  src/inner_connection.rs
  src/lib.rs
Labels: enhancement

#21 enable publish crates in CI
  .github/workflows/rust.yaml
  Cargo.toml
  libduckdb-sys/Cargo.toml
Labels: feature

#25 Fix u64/UBigInt 'FromSql' trait impl
  src/types/from_sql.rs
Labels: fix

#26 add test for uint
  src/types/from_sql.rs
Labels: test

#28 support hugeint
  src/row.rs
  src/statement.rs
  src/types/from_sql.rs
Labels: fix
